### ISSUE TITLE
Make trigger box trap + screen shake

### ISSUE THREAD

**Issue by thomastran8** [thomastran8/PyramidEscape#12]
This will be an trigger collider box that if a player walks into it then it will activate its references plus a screen shake. Great for surprise events. Just to note that I scrapped the idea of pressure plates.

**Comment by dbelliss** [comment]
Screen shake is callable from anywhere with GameManager.UI.ShakeCamera(.4f, 2f);

**Comment by thomastran8** [comment]
Done
