### ISSUE TITLE
Make save point (optional if levels are short enough)

### ISSUE THREAD

**Issue by thomastran8** [thomastran8/PyramidEscape#17]
This might be a statue or something similar, if the player right clicks it the player will save their location in front of the statue. The save location would be an empty transform in front of the statue. When the player dies they get teleported to the save location. Add a visual gimmick on statue like a torch on the statue to let them know that the save point is active.

Dependent on right click interact script

**Comment by dbelliss** [comment]
Currently using a large bucket as the checkpoint, but it works

**Comment by dbelliss** [comment]
Added table with candles. Right click to activate and candles turn on. Player will respawn from most recently used table.
