### ISSUE TITLE
Make next level door

### ISSUE THREAD

**Issue by thomastran8** [thomastran8/PyramidEscape#22]
This teleports you to the next scene

**Comment by dbelliss** [comment]
Currently using a cube boulder as the next level door, but it works

**Comment by dbelliss** [comment]
player health and potions are refreshed on new level, not sure if we want to change this since we don't have a health pickup

**Comment by dbelliss** [comment]
Game manager and sound manager are marked as "Don't Destroy On Load"

**Comment by dbelliss** [comment]
Added prefab with trigger to take player to next level
