### ISSUE TITLE
Level 5: Boss fight

### ISSUE THREAD

**Issue by thomastran8** [thomastran8/PyramidEscape#27]
Player fights a humongous boss. Potion re-spawns in center of arena. Player interacts with next level door

**Comment by dbelliss** [comment]
Potions spawn in each corner, 2 max at all times. Boss is giant axe mummy. Press level to spawn boss. After entering room all doors close. Boss has a slider on UI to indicate remaining HP.

**Comment by dbelliss** [comment]
Added minions and warning sign.
